---
enable_worker_cronjobs: &enable_cron true
enable_purge_cronjobs: &enable_purge true
disable_worker_email: &disable_email true
dlrn_server_type: primary
dlrn_enable_https: false
dlrn_manage_letsencrypt: false
dlrn_host: trunk-centos9
web_domain: '10.0.79.140'
dlrn_workers:
  centos10-master-preview:
    distro: 'centos10'
    target: 'centos10-master-preview'
    distgit_branch: 'rpm-master'
    distro_branch: 'master'
    disable_email: true
    enable_cron: false
    enable_purge: false
    symlinks: ['/var/www/html/centos10-master-preview']
    release: 'epoxy-uc'
    baseurl: 'http://{{ web_domain }}/centos10-master-preview'
    pkginfo_driver: 'dlrn.drivers.rdoinfo.RdoInfoDriver'
    build_driver: 'dlrn.drivers.mockdriver.MockBuildDriver'
    db_connection: 'sqlite:///commits.sqlite'
    mock_tmpfs_enable: true
    fallback_to_master: true
    include_srpm_in_repo: true
    enable_deps_sync: false
    enable_brs_sync: false
    use_components: true
    mock_config: 'centos10stream.cfg.j2'
    uid: 1020
    gid: 1020
