---
- name: "Upload dlrn-deps.repo file"
  tags: [extra]
  ansible.builtin.template:
    src: "templates/dlrn-deps.repo.j2"
    dest: "/home/{{ worker_name }}/data/repos/dlrn-deps.repo"
    owner: "{{ worker_name }}"
    group: "{{ worker_name }}"
    mode: '0644'

- name: "Create delorean-deps.repo symlink"
  tags: [extra]
  ansible.builtin.file:
    src: "/home/{{ worker_name }}/data/repos/dlrn-deps.repo"
    dest: "/home/{{ worker_name }}/data/repos/delorean-deps.repo"
    owner: "{{ worker_name }}"
    group: "{{ worker_name }}"
    state: link

- name: "Create deps and build-deps repo"
  tags: [extra, test]
  ansible.builtin.file:
    path: "/home/{{ worker_name }}/data/repos/{{ item }}"
    owner: "{{ worker_name }}"
    group: "{{ worker_name }}"
    state: directory
    mode: '0755'
  with_items:
    - "deps"
    - "build-deps"
