all:
  children:
    dlrn:
      hosts:
        osp-trunk-deps: {}
    rdo-cs10:
      hosts:
        rdo-cs10: {}
  hosts:
    osp-trunk-deps:
      ansible_host: '10.0.78.125'
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: centos
    rdo-cs10:
      ansible_host: '10.0.79.140'
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
