- name: Deploy DLRN trunk
  hosts: all
  become: yes
  tasks:
    - name: Pre-install some packages
      tags: [pre]
      package:
        name: "{{ item }}"
      with_items: "{{ base_packages }}"

    - name: "Include firewalld"
      tags: [pre]
      include_role:
        name: "service/firewalld"

    - name: "Include dlrn"
      tags: [dlrn]
      include_role:
        name: "dlrn"
        apply:
          tags:
             - dlrn

    - name: "Include post tasks"
      tags: [cs10, tooling, test]
      ansible.builtin.include_tasks:
        file: "post.yaml"

  handlers:
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
