- name: poc dlrn deps
  hosts: rdo-cs10
  become: yes
  tasks:
    - name: Pre-install some packages
      package:
        name: "{{ item }}"
      with_items: "{{ base_packages }}"

    - name: "Include firewalld"
      include_role:
        name: "service/firewalld"

    - name: "Include dlrn"
      include_role:
        name: "dlrn"
