- name: Deploy DLRN trunk
  hosts: all
  become: yes
  tasks:
    - name: Pre-install some packages
      package:
        name: "{{ item }}"
      with_items: "{{ base_packages }}"

    - name: "Include firewalld"
      include_role:
        name: "service/firewalld"

    - name: "Include dlrn"
      include_role:
        name: "dlrn"

- name: Extra tasks for CS10 Trunk
  hosts: cs10
  become: yes
  tasks:
    - name: "Include extra tasks"
      tags: [cs10, extra]
      ansible.builtin.include_tasks:
        file: "extra-cs10.yaml"
